spring.application.name=url
spring.mongodb.authentication-database=admin
spring.data.mongodb.auto-index-creation=true
spring.mongodb.uri=mongodb://localhost:27017/shortener_db
spring.data.mongodb.username=admin
spring.data.mongodb.password=123

